src/opinioxx/base/urls.py
from django.urls import path

from opinioxx.base import views
from django.contrib.auth import views as auth_views

from opinioxx.base.forms import LoginForm
from opinioxx.base.models import Project

app_name = 'base'

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/login', auth_views.LoginView.as_view(authentication_form=LoginForm), name='login'),
    path('accounts/password_reset',
         auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetView.as_view(template_name='registration/password_reset_success.html'),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/passwordresetconfirm.html'),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/passwordresetcomplete.html'),
         name='password_reset_confirm'),
    path('accounts/register', views.register, name='register'),
    path('profile', views.profile, name='profile'),
    path('profile/changepassword', views.profile_changepassword, name='profile_changepassword'),
    path('profile/emailsettings', views.profile_emailsettings, name='profile_emailsettings'),
    path('new', views.newproject, name='newproject'),
    path('<int:project_id>', views.project, name='project'),
    path('<int:project_id>/c', views.project, {'compact': True}, name='projectcompact'),
    path('archive', views.index, {'state': Project.ARCHIVED}, name='projectarchive'),
    path('<int:project_id>/edit', views.newproject, name='editproject'),
    path('<int:project_id>/new', views.newidea, name='newidea'),
    path('<int:project_id>/<int:idea_id>/detail', views.idea, name='idea'),
    path('<int:project_id>/archive', views.project, {'archive': True}, name='archive'),
    path('<int:project_id>/c/archive', views.project, {'archive': True, 'compact': True}, name='archivecompact'),
    path('<int:project_id>/vote', views.vote, name='vote'),
    path('cron', views.cron, name='cron'),
]

src/opinioxx/urls.py
import importlib

from django.apps import apps
from django.contrib import admin
from django.urls import path, include

plugin_patterns = []
for app in apps.get_app_configs():
    if hasattr(app, 'OpinioxxPlugin'):
        if importlib.util.find_spec(f'{app.name}.utils'):
            module = importlib.import_module(f'{app.name}.urls')
            plugin_patterns.append(path('', include(module, app.label)))

urlpatterns = [
    path('', include((plugin_patterns, 'plugins'))),
    path('', include('opinioxx.base.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

src/opinioxx/base/models/comment.py
from django.db import models

from opinioxx import settings


class Comment(models.Model):
    """ Stores a comment related to an idea. Comments with a specific category change the state of the idea. """
    CLOSE = 'C'
    ACCEPT = 'A'
    REOPEN = 'R'
    NORMAL = 'N'
    content = models.CharField(max_length=5000)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    idea = models.ForeignKey('Idea', on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    category = models.CharField(max_length=1, blank=True, default=NORMAL, choices=[
        (CLOSE, 'closes'),
        (ACCEPT, 'accepts'),
        (REOPEN, 'reopens'),
        (NORMAL, 'normal')
    ])

src/opinioxx/base/models/favorite.py
from django.conf import settings
from django.db import models


class Favorite(models.Model):
    """ Stores a favourite point for an Idea """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    idea = models.ForeignKey('Idea', on_delete=models.CASCADE)

src/opinioxx/base/models/global_settings.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone


class GlobalSettings(models.Model):
    """ stores application wide settings """
    last_cron_run = models.DateField(default=timezone.now)  # defines the last successful run of the cron job

    def save(self, *args, **kwargs):
        """ custom save function to ensure, that only one object of this type can exist """
        if not self.id and GlobalSettings.objects.exists():
            raise ValidationError('Only one global settings object allowed!')
        return super().save(*args, **kwargs)

src/opinioxx/base/models/idea.py
from django.db import models
from django.db.models import Sum


class Idea(models.Model):
    """ A single idea or suggestion what could be made better in a project. """
    OPEN = 'O'
    SUCCESS = 'Y'
    REJECTED = 'N'
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=500, null=True, blank=True)
    project = models.ForeignKey('Project', on_delete=models.CASCADE)
    state = models.CharField(max_length=1, default=OPEN, choices=[
        (OPEN, 'open'),
        (SUCCESS, 'success'),
        (REJECTED, 'rejected')
    ])
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_vote_value(self):
        """ returns the current value of votes and favorites for this idea """
        favorites_value = round(self.favorite_set.all().count() * self.project.favorite_value)
        votes_value = self.vote_set.aggregate(Sum('value'))['value__sum']
        if not votes_value:
            votes_value = 0
        return votes_value + favorites_value

    def get_css(self):
        """ returns the css classes set to the feedback depending on the current rating """
        if self.get_vote_value() > 0:
            return 'bg-success positive'
        elif self.get_vote_value() < 0:
            return 'bg-danger negative'
        else:
            return 'bg-dark text-light'

    def get_vote_count(self):
        return self.vote_set.count()

    def get_star_count(self):
        return self.favorite_set.count()

    def get_comment_count(self):
        return self.comment_set.count()

    def is_active(self):
        return self.state == Idea.OPEN

src/opinioxx/base/models/vote.py
from django.conf import settings
from django.db import models


class Vote(models.Model):
    """ Stores a vote for an Idea """
    POSITIVE = 1
    NEUTRAL = 0
    NEGATIVE = -1
    value = models.IntegerField(choices=[
        (POSITIVE, 'positive'),
        (NEUTRAL, 'neutral'),
        (NEGATIVE, 'negative'),
    ])
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    idea = models.ForeignKey('Idea', on_delete=models.CASCADE)

src/opinioxx/base/views.py
import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model, get_user, update_session_auth_hash
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.db.models.functions import Lower
from django import forms
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse

from opinioxx.base.forms import IdeaForm, ProjectForm, CustomUserCreationForm, CommentForm, \
    CustomPasswordChangeForm, EmailSettingsForm, VoteForm
from opinioxx.base.models import Idea, Vote, User, Favorite, Project, Comment, GlobalSettings
from opinioxx.base.signals import access_allowed_ideas, run_cron_jobs


def index(request, state=Project.OPEN):
    """ index-view to display available projects """
    user = get_user(request)
    if state == Project.OPEN:
        new_project_allowed = (settings.ALLOW_NEW_PROJECTS and not user.is_anonymous) or request.user.is_superuser
    else:
        new_project_allowed = False
    context = {
        'new_project_allowed': new_project_allowed,
        'projects': User.get_projects(user, state),
    }
    return render(request, 'base/index.html', context)


def register(request):
    """ view to register a new user """
    if User.objects.count() > 0 and not settings.ALLOW_USER_REGISTRATION:
        raise PermissionDenied
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            if User.objects.count() == 1:
                user.is_superuser = True
                user.is_staff = True
                user.save()
            return HttpResponseRedirect(reverse('base:login'))
    return render(request, 'registration/register.html', {'form': form})


def profile(request):
    """ view to display the profile page """
    user = get_user(request)
    if user.is_anonymous:
        raise PermissionDenied
    tab = request.GET.get('tab', 'password')
    form_passwordchange = CustomPasswordChangeForm(request.user)
    form_emailsettings = EmailSettingsForm(request.user, instance=request.user)
    return render(request, 'base/profile.html', {
        'form_passwordchange': form_passwordchange,
        'form_emailsettings': form_emailsettings,
        'tab': tab,
    })


def profile_changepassword(request):
    """ view to change the password on the profile page """
    user = get_user(request)
    if user.is_anonymous:
        raise PermissionDenied
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Dein Passwort wurde erfolgreich gespeichert!')
        else:
            messages.error(request,
                           'Dein Passwort konnte nicht gespeichert werden. Bitte behebe die untenstehenden Fehler.')
    response = redirect('base:profile')
    response['Location'] += '?tab=password'
    return response


def profile_emailsettings(request):
    """ view to change the email settings on the profile page """
    user = get_user(request)
    if user.is_anonymous:
        raise PermissionDenied
    if request.method == 'POST':
        form = EmailSettingsForm(request.user, request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Deine Einstellungen wurden erfolgreich gespeichert!')
        else:
            messages.error(request, 'Deine Einstellungen konnten nicht erfolgreich gespeichert werden')
    response = redirect('base:profile')
    response['Location'] += '?tab=email'
    return response


def newproject(request, project_id=None):
    """ view to create a new project or edit an existing one """
    user = get_user(request)
    if project_id:
        if user.is_anonymous or not Project.objects.filter(id=project_id,
                                                           admins__id=user.id).exists() and not user.is_superuser:
            raise PermissionDenied
        project = get_object_or_404(Project, id=project_id)
        form = ProjectForm(instance=project)
        form.fields['anonymous_votes'].disabled = True
        context = {
            'form': form,
            'title': 'Projekt editieren',
            'success': False,
            'edit': True,
        }
        if request.method == 'POST':
            form = ProjectForm(request.POST, instance=project)
            if 'delete' in request.POST:
                project.delete()
                return HttpResponseRedirect(reverse('base:index'))
            elif form.is_valid():
                p = form.save()
                p.add_notifications()
                context['success'] = True
        return render(request, 'base/newproject.html', context)
    else:
        if (not settings.ALLOW_NEW_PROJECTS or user.is_anonymous) and not request.user.is_superuser:
            raise PermissionDenied
        context = {
            'form': ProjectForm(),
            'title': 'Neues Projekt anlegen',
            'success': False,
            'edit': False,
        }
        if request.method == 'POST':
            form = ProjectForm(request.POST)
            if form.is_valid():
                p = form.save()
                p.add_notifications()
                context['success'] = True
        return render(request, 'base/newproject.html', context)


def cron(request):
    """ view to handle recurring tasks via curl requests """
    globalsettings = GlobalSettings.objects.get_or_create(id=1)[0]
    # send daily notifications
    if globalsettings.last_cron_run < datetime.date.today():
        for user in User.objects.filter(notify_interval=1).all():
            user.send_notification()
    # send weekly notifications
    if globalsettings.last_cron_run.weekday() + (datetime.date.today() - globalsettings.last_cron_run).days > 7:
        for user in User.objects.filter(notify_interval=7).all():
            user.send_notification()
    # send monthly notifications
    if datetime.date.today().day == 1 and globalsettings.last_cron_run.month != datetime.date.today().month:
        for user in User.objects.filter(notify_interval=30).all():
            user.send_notification()
    run_cron_jobs.send(request)
    globalsettings.last_cron_run = datetime.date.today()
    globalsettings.save()
    return HttpResponse('OK')


def newidea(request, project_id):
    """ view to store a new idea for a given project """
    user = get_user(request)
    project = get_object_or_404(Project, id=project_id)
    if not project.access_allowed(user) or project.archived():
        raise PermissionDenied
    context = {
        'form': IdeaForm(),
        'new_feedback_text': project.new_idea_description,
        'success': False,
        'project': project,
    }
    if request.method == 'POST':
        form = IdeaForm(request.POST)
        if form.is_valid():
            try:
                Idea.objects.get(title=form.cleaned_data['title'], project_id=project.id)
                messages.warning(request, 'Es existiert bereits ein Feedback mit identischem Titel!')
                context['form'] = IdeaForm(request.POST)
            except ObjectDoesNotExist:
                idea = Idea(title=form.cleaned_data['title'], description=form.cleaned_data['description'],
                            project=project)
                idea.save()
                if form.cleaned_data['upvote']:
                    # upvote the idea directly
                    if project.voting_allowed(user):
                        if user.is_anonymous:
                            if not 'idea_ids' in request.session:
                                request.session['idea_ids'] = []
                            request.session['idea_ids'].append(idea.id)
                            request.session.modified = True
                        else:
                            if project.anonymous_votes:
                                Vote(user=user, idea=idea).save()
                            else:
                                Vote(user=user, idea=idea, value=Vote.POSITIVE).save()
                    idea.save()
                context['success'] = True
    return render(request, 'base/newidea.html', context)


def project(request, project_id, archive=False, compact=False):
    """ project-view to show all associated ideas """
    user = get_user(request)
    project = get_object_or_404(Project, id=project_id)
    if not project.access_allowed(user):
        raise PermissionDenied
    request.session['compactview'] = compact
    request.session.modified = True
    if archive:
        ideas = project.idea_set.filter(state=Idea.SUCCESS).all() | project.idea_set.filter(state=Idea.REJECTED).all()
    else:
        ideas = project.idea_set.filter(state=Idea.OPEN).all()
    priority = 100
    for receiver, response in access_allowed_ideas.send(request, ideas=ideas, user=user, project=project):
        if response and response['priority'] and response['value'] and response['priority'] < priority:
            ideas = response['value']
            priority = response['priority']
    ideas = sorted(ideas, key=lambda x: -x.get_vote_value())  # sort ideas
    context = {
        'project': project,
        'user': user,
        'show_settings': user in project.admins.all(),
        'ideas': ideas,
        'archive': archive if project.state != Project.ARCHIVED else True,
        'compact': compact,
        'view': 'project',
    }
    return render(request, 'base/project.html', context)


def vote(request, project_id):
    """ view to store a vote and redirect to project page """
    user = get_user(request)
    project = get_object_or_404(Project, id=project_id)
    idea = None

src/opinioxx/base/templates/base/index.html
{# renders the project overview on the startpage #}
{% extends "base/base.html" %}
{% load static %}
{% load template_tags %}

{% block content %}
    <div class="container-lg align-self-center">
        {% if not projects %}
            <div class="bg-secondary shadow-lg rounded-lg d-flex flex-column mb-3">
                <div class="d-flex flex-row rounded-top bg-dark">
                    <h2 class="h2 m-0 p-2 text-light text-break flex-fill">Kein Projekt gefunden</h2>
                </div>
                <div class="d-flex flex-column">
                    <p class="text-light pt-2 pl-2 pr-2 flex-fill text-break mb-0 pb-0">
                        Aktuell gibt es kein Projekt, für das du berechtigt bist. Bitte melde dich an, erstelle selbst
                        ein Projekt oder kontaktiere einen Projektadministrator, um Zugriff auf ein existierendes
                        Projekt zu erhalten.
                    </p>
                </div>
            </div>
        {% endif %}
        {% if new_project_allowed %}
            <a class="btn btn-success btn-block" href="{% url 'base:newproject' %}">+ Neues Projekt
                anlegen +</a>
        {% endif %}
        {% for project in projects %}
            <div class="bg-secondary shadow-lg rounded-lg d-flex flex-column mt-3">
                <div class="d-flex flex-row rounded-top bg-dark">
                    <h2 class="h2 m-0 p-2 text-light text-break flex-fill">
                        {% if request.session.compactview %}
                            <a class="text-light" href="{% url 'base:projectcompact' project.id %}">
                        {% else %}
                            <a class="text-light" href="{% url 'base:project' project.id %}">
                        {% endif %}
                        {{ project.name }}
                        </a>
                    </h2>
                    {% signal 'opinioxx.base.signals.display_project_icons' project=project %}
                </div>
                <div class="d-flex flex-column">
                    <p class="text-light pt-2 pl-2 pr-2 flex-fill text-break mb-0 pb-0">{{ project.description }}</p>
                    {% if request.session.compactview %}
                        <a class="btn btn-info align-self-end text-nowrap"
                           href="{% url 'base:projectcompact' project.id %}">
                    {% else %}
                        <a class="btn btn-info align-self-end text-nowrap"
                           href="{% url 'base:project' project.id %}">
                    {% endif %}
                    Projekt öffnen
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}

src/opinioxx/base/templates/base/navigation.html
{# renders the navigation bar #}
{% load static %}

<nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <a class="navbar-brand" href="{% url 'base:index' %}">{{ site_title }}</a>
        <ul class="navbar-nav mr-auto">
            {% if open_projects %}
                <li class="nav-item text-center">
                    <div class="btn-group">
                        <a href="{% url 'base:index' %}" class="btn nav-link bg-dark">Projekte</a>
                        <button type="button" class="btn nav-link dropdown-toggle dropdown-toggle-split bg-dark"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="sr-only">Toggle Project-Dropdown</span>
                        </button>
                        <div class="dropdown-menu bg-dark">
                            {% for project in open_projects %}
                                {% if request.session.compactview %}
                                    <a class="dropdown-item text-light bg-dark"
                                       href="{% url 'base:projectcompact' project.id %}">
                                        {{ project.name }}
                                    </a>
                                {% else %}
                                    <a class="dropdown-item text-light bg-dark"
                                       href="{% url 'base:project' project.id %}">{{ project.name }}</a>
                                {% endif %}
                            {% endfor %}
                            <hr class="m-0">
                            <a class="dropdown-item text-light bg-dark" href="{% url 'base:projectarchive' %}">
                                Archiv</a>
                        </div>
                    </div>
                </li>
            {% endif %}
            {% if project %}
                <li class="nav-item text-center">
                    <div class="btn-group">
                        {% if request.session.compactview %}
                            <a href="{% url 'base:projectcompact' project.id %}"
                               class="btn nav-link bg-dark">
                        {% else %}
                            <a href="{% url 'base:project' project.id %}" class="btn nav-link bg-dark">
                        {% endif %}
                        Feedback-Übersicht
                        </a>
                        <button type="button" class="btn nav-link dropdown-toggle dropdown-toggle-split bg-dark"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="sr-only">Toggle Feedback-Overview-Dropdown</span>
                        </button>
                        <div class="dropdown-menu bg-dark">
                            <a class="dropdown-item text-light bg-dark"
                               href="{% url 'base:newidea' project.id %}">Feedback eintragen</a>
                            <hr class="m-0">
                            {% if request.session.compactview %}
                                <a class="dropdown-item text-light bg-dark {% if request.path == url %}active{% endif %}"
                                   href="{% url 'base:archivecompact' project.id %}">Feedback-Archiv</a>
                            {% else %}
                                <a class="dropdown-item text-light bg-dark {% if request.path == url %}active{% endif %}"
                                   href="{% url 'base:archive' project.id %}">Feedback-Archiv</a>
                            {% endif %}
                        </div>
                    </div>
                </li>
            {% endif %}
        </ul>
        {% if project %}
            {% if view == 'project' %}
                {% if compact %}
                    {% if archive %}
                        <a type="button" class="btn btn-info btn-sm mr-5" data-toggle="button" aria-pressed="true"
                           href="{% url 'base:archive' project.id %}">
                            Kompaktansicht
                        </a>
                    {% else %}
                        <a type="button" class="btn btn-info btn-sm mr-5" data-toggle="button" aria-pressed="true"
                           href="{% url 'base:project' project.id %}">
                            Kompaktansicht
                        </a>
                    {% endif %}
                {% else %}
                    {% if archive %}
                        <a type="button" class="btn btn-secondary btn-sm mr-5" data-toggle="button" aria-pressed="false"
                           href="{% url 'base:archivecompact' project.id %}">
                            Kompaktansicht
                        </a>
                    {% else %}
                        <a type="button" class="btn btn-secondary btn-sm mr-5" data-toggle="button" aria-pressed="false"
                           href="{% url 'base:projectcompact' project.id %}">
                            Kompaktansicht
                        </a>
                    {% endif %}
                {% endif %}
            {% endif %}
        {% endif %}
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle bg-dark btn" href="" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right bg-dark" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item text-light bg-dark"
                           href="{% url 'base:profile' %}">
                            Profil
                        </a>
                        <a class="dropdown-item text-light bg-dark"
                           href="{% url 'logout' %}">
                            Logout
                        </a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'base:login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

src/opinioxx/base/templates/base/newidea.html
{# form for new ideas #}
{% extends "base/base.html" %}
{% load static %}
{% load template_tags %}

{% block content %}
    <div class="container-lg align-self-center">
        {% if success %}
            <div class="rounded-lg bg-secondary text-light text-center p-2 shadow-lg border border-success">
                <h2 class="text-break">Dein Feedback wurde erfolgreich gespeichert!</h2>
                <p class="text-break">Bitte beachte, dass es unter Umständen nicht öffentlich sichtbar ist, bis es eine
                    Mindestanzahl an Stimmen erhalten hat.</p>
                <div class="text-break">Zurück zur Übersicht in
                    <div class="d-inline" id="time">3</div>
                    Sekunden.
                </div>
                <br>
                {% if request.session.compactview %}
                    <a href="{% url 'base:projectcompact' project.id %}"
                       class="align-self-center btn btn-info">
                {% else %}
                    <a href="{% url 'base:project' project.id %}" class="align-self-center btn btn-info">
                {% endif %}
                zurück zur Übersicht
                </a>
            </div>
            <script>
                window.setTimeout(function () {
                    {% if request.session.compactview %}
                        window.location.href = "{% url 'base:projectcompact' project.id %}";
                    {% else %}
                        window.location.href = "{% url 'base:project' project.id %}";
                    {% endif %}
                }, 3000);
                setInterval(function () {
                    var newTime = (parseInt(document.getElementById("time").innerHTML) - 1).toString();
                    document.getElementById("time").innerHTML = newTime;
                }, 1000);
            </script>
        {% else %}
            {% if messages %}
                {% for message in messages %}
                    <div class="bg-danger mb-5 text-center text-light rounded">
                        <p class="m-2 p-1">{{ message }}</p>
                    </div>
                {% endfor %}
            {% endif %}
            <div class="container-lg bg-dark rounded-lg d-flex flex-row align-items-stretch p-0 text-light
                justify-content-center mb-2">
                <h1 class="text-break">Neues Feedback eintragen</h1>
            </div>
            <div class="text-break container-lg bg-secondary rounded-lg d-flex flex-row align-items-stretch p-2
                text-light justify-content-center mb-5 text-justify shadow-lg">
                {{ new_feedback_text }}
            </div>
            <div class="container-lg bg-secondary rounded-lg d-flex flex-row align-items-stretch p-0 mt-3 shadow-lg">
                <div class="rounded-left p-0 d-flex flex-column bg-dark"
                     style="min-width: 50px; width: 50px;">
                    <div class="flex-fill m-0 text-center row align-items-center">
                        <h2 class="text-light m-0 flex-fill">0</h2>
                    </div>
                </div>
                <div class="d-flex flex-column flex-fill">
                    <form method="post" action="{% url 'base:newidea' project.id %}">
                        {% csrf_token %}
                        <h2 class="h2 align-self-stretch bg-dark m-0 p-2 text-light rounded-right text-break">
                            {{ form.title }}
                        </h2>
                        <div class="p-2 text-light">
                            {{ form.description }}
                            {% voting_allowed project.id None as voting_allowed %}
                            {% if voting_allowed %}
                                {{ form.upvote.label_tag }} {{ form.upvote }}
                            {% endif %}
                            <button type="submit" class="btn btn-success btn-block mt-3">Speichern</button>
                        </div>
                    </form>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}